[package]
name = "workout_track"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"]}
# clap = {version = "4", features = ["cargo"] }
